default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  prepared_statement: false
  database: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  prepared_statement: false
  database: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  prepared_statement: false
  database: <%= ENV['DATABASE_URL'] %>
